#!/usr/bin/env bash

set -e

# Get the directory of the project (application-manager)
APPLICATION_MANAGER_DIR="$(dirname "$(readlink -f "$0")")"
# Load the configuration and common files
. "$APPLICATION_MANAGER_DIR/config.env"
. "$APPLICATION_MANAGER_DIR/common"

# Path to the monitor script
MANAGER_SCRIPT="$APPLICATION_MANAGER_DIR/manager"
# Path to the application linker script
APPLICATION_LINKER="$APPLICATION_MANAGER_DIR/apps_linker"

# systemd service file name and directory
SERVICE_FILE="applications-manager.service"
SERVICE_FILE_DIR="/etc/systemd/system/$SERVICE_FILE"

# Check if the monitor script exists
if [ ! -f "$MANAGER_SCRIPT" ]; then
    log "Monitor script not found at $MANAGER_SCRIPT. Please create the script first."
    exit 1
fi

# Check if the application linker script exists
if [ ! -f "$APPLICATION_LINKER" ]; then
    log "Application linker script not found at $APPLICATION_LINKER. Please create the script first."
    exit 1
fi

# Ensure the application-manager folder scripts are executable recursively
sudo chmod +x "$APPLICATION_MANAGER_DIR"

# Restart the service if it already exists
restart_systemctl_service $SERVICE_FILE

log "Creating systemd service file at $SERVICE_FILE_DIR..."

# Create the service file
echo "================================================="
cat <<EOF | sudo tee "$SERVICE_FILE_DIR"
[Unit]
Description=Monitor applications-manager Directory for Changes and Execute applications manager script on change.

[Service]
ExecStart=$MANAGER_SCRIPT
Restart=always
User=root

[Install]
WantedBy=multi-user.target
EOF
echo "================================================="

# Reload systemd to recognize the new service
sudo systemctl daemon-reload

# Enable and start the service
sudo systemctl enable $SERVICE_FILE
sudo systemctl start $SERVICE_FILE

log "Service $SERVICE_FILE created, enabled, and started."

# run the application linker script
log "running the linker script for the first time..."
sudo $APPLICATION_LINKER

log "Setup complete."
